//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("JOMSQLDBModel", "CatParent", "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JomDBForm.Category), "Category1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JomDBForm.Category))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("JOMSQLDBModel", "CatSection", "Sections", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JomDBForm.Sections), "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JomDBForm.Category))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("JOMSQLDBModel", "ZoneRegion", "Zone", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JomDBForm.Zone), "Region", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JomDBForm.Region))]

// Original file name:
// Generation date: 5/28/2009 5:42:43 PM
namespace JomDBForm
{
    
    /// <summary>
    /// There are no comments for JOMSQLDBEntities in the schema.
    /// </summary>
    public partial class JOMSQLDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new JOMSQLDBEntities object using the connection string found in the 'JOMSQLDBEntities' section of the application configuration file.
        /// </summary>
        public JOMSQLDBEntities() : 
                base("name=JOMSQLDBEntities", "JOMSQLDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new JOMSQLDBEntities object.
        /// </summary>
        public JOMSQLDBEntities(string connectionString) : 
                base(connectionString, "JOMSQLDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new JOMSQLDBEntities object.
        /// </summary>
        public JOMSQLDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "JOMSQLDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Category> Category
        {
            get
            {
                if ((this._Category == null))
                {
                    this._Category = base.CreateQuery<Category>("[Category]");
                }
                return this._Category;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Category> _Category;
        /// <summary>
        /// There are no comments for DataRecord in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<DataRecord> DataRecord
        {
            get
            {
                if ((this._DataRecord == null))
                {
                    this._DataRecord = base.CreateQuery<DataRecord>("[DataRecord]");
                }
                return this._DataRecord;
            }
        }
        private global::System.Data.Objects.ObjectQuery<DataRecord> _DataRecord;
        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Region> Region
        {
            get
            {
                if ((this._Region == null))
                {
                    this._Region = base.CreateQuery<Region>("[Region]");
                }
                return this._Region;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Region> _Region;
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Sections> Sections
        {
            get
            {
                if ((this._Sections == null))
                {
                    this._Sections = base.CreateQuery<Sections>("[Sections]");
                }
                return this._Sections;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Sections> _Sections;
        /// <summary>
        /// There are no comments for Zone in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Zone> Zone
        {
            get
            {
                if ((this._Zone == null))
                {
                    this._Zone = base.CreateQuery<Zone>("[Zone]");
                }
                return this._Zone;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Zone> _Zone;
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
        /// <summary>
        /// There are no comments for DataRecord in the schema.
        /// </summary>
        public void AddToDataRecord(DataRecord dataRecord)
        {
            base.AddObject("DataRecord", dataRecord);
        }
        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        public void AddToRegion(Region region)
        {
            base.AddObject("Region", region);
        }
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        public void AddToSections(Sections sections)
        {
            base.AddObject("Sections", sections);
        }
        /// <summary>
        /// There are no comments for Zone in the schema.
        /// </summary>
        public void AddToZone(Zone zone)
        {
            base.AddObject("Zone", zone);
        }
    }
    /// <summary>
    /// There are no comments for JOMSQLDBModel.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="JOMSQLDBModel", Name="Category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="dType">Initial value of DType.</param>
        public static Category CreateCategory(global::System.Guid categoryID, int dType)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            category.DType = dType;
            return category;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this.ReportPropertyChanging("CategoryID");
                this._CategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryID");
                this.OnCategoryIDChanged();
            }
        }
        private global::System.Guid _CategoryID;
        partial void OnCategoryIDChanging(global::System.Guid value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ArName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ArName
        {
            get
            {
                return this._ArName;
            }
            set
            {
                this.OnArNameChanging(value);
                this.ReportPropertyChanging("ArName");
                this._ArName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ArName");
                this.OnArNameChanged();
            }
        }
        private string _ArName;
        partial void OnArNameChanging(string value);
        partial void OnArNameChanged();
        /// <summary>
        /// There are no comments for Property EnName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this._EnName;
            }
            set
            {
                this.OnEnNameChanging(value);
                this.ReportPropertyChanging("EnName");
                this._EnName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EnName");
                this.OnEnNameChanged();
            }
        }
        private string _EnName;
        partial void OnEnNameChanging(string value);
        partial void OnEnNameChanged();
        /// <summary>
        /// There are no comments for Property DType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int DType
        {
            get
            {
                return this._DType;
            }
            set
            {
                this.OnDTypeChanging(value);
                this.ReportPropertyChanging("DType");
                this._DType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DType");
                this.OnDTypeChanged();
            }
        }
        private int _DType;
        partial void OnDTypeChanging(int value);
        partial void OnDTypeChanged();
        /// <summary>
        /// There are no comments for ChildCategories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("JOMSQLDBModel", "CatParent", "Category1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Category> ChildCategories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Category>("JOMSQLDBModel.CatParent", "Category1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Category>("JOMSQLDBModel.CatParent", "Category1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ParentCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("JOMSQLDBModel", "CatParent", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category ParentCategory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("JOMSQLDBModel.CatParent", "Category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("JOMSQLDBModel.CatParent", "Category").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ParentCategory in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> ParentCategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("JOMSQLDBModel.CatParent", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("JOMSQLDBModel.CatParent", "Category", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OwnerSection in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("JOMSQLDBModel", "CatSection", "Sections")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Sections OwnerSection
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Sections>("JOMSQLDBModel.CatSection", "Sections").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Sections>("JOMSQLDBModel.CatSection", "Sections").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OwnerSection in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Sections> OwnerSectionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Sections>("JOMSQLDBModel.CatSection", "Sections");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Sections>("JOMSQLDBModel.CatSection", "Sections", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for JOMSQLDBModel.DataRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RecordID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="JOMSQLDBModel", Name="DataRecord")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class DataRecord : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new DataRecord object.
        /// </summary>
        /// <param name="recordID">Initial value of RecordID.</param>
        /// <param name="dataFile">Initial value of DataFile.</param>
        /// <param name="dataEntryDate">Initial value of DataEntryDate.</param>
        /// <param name="recordDataType">Initial value of RecordDataType.</param>
        /// <param name="belongToZone">Initial value of BelongToZone.</param>
        public static DataRecord CreateDataRecord(global::System.Guid recordID, string dataFile, global::System.DateTime dataEntryDate, int recordDataType, bool belongToZone)
        {
            DataRecord dataRecord = new DataRecord();
            dataRecord.RecordID = recordID;
            dataRecord.DataFile = dataFile;
            dataRecord.DataEntryDate = dataEntryDate;
            dataRecord.RecordDataType = recordDataType;
            dataRecord.BelongToZone = belongToZone;
            return dataRecord;
        }
        /// <summary>
        /// There are no comments for Property RecordID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid RecordID
        {
            get
            {
                return this._RecordID;
            }
            set
            {
                this.OnRecordIDChanging(value);
                this.ReportPropertyChanging("RecordID");
                this._RecordID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RecordID");
                this.OnRecordIDChanged();
            }
        }
        private global::System.Guid _RecordID;
        partial void OnRecordIDChanging(global::System.Guid value);
        partial void OnRecordIDChanged();
        /// <summary>
        /// There are no comments for Property Caption in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption
        {
            get
            {
                return this._Caption;
            }
            set
            {
                this.OnCaptionChanging(value);
                this.ReportPropertyChanging("Caption");
                this._Caption = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Caption");
                this.OnCaptionChanged();
            }
        }
        private string _Caption;
        partial void OnCaptionChanging(string value);
        partial void OnCaptionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailFile in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailFile
        {
            get
            {
                return this._ThumbnailFile;
            }
            set
            {
                this.OnThumbnailFileChanging(value);
                this.ReportPropertyChanging("ThumbnailFile");
                this._ThumbnailFile = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ThumbnailFile");
                this.OnThumbnailFileChanged();
            }
        }
        private string _ThumbnailFile;
        partial void OnThumbnailFileChanging(string value);
        partial void OnThumbnailFileChanged();
        /// <summary>
        /// There are no comments for Property DataFile in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFile
        {
            get
            {
                return this._DataFile;
            }
            set
            {
                this.OnDataFileChanging(value);
                this.ReportPropertyChanging("DataFile");
                this._DataFile = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DataFile");
                this.OnDataFileChanged();
            }
        }
        private string _DataFile;
        partial void OnDataFileChanging(string value);
        partial void OnDataFileChanged();
        /// <summary>
        /// There are no comments for Property DataEntryDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DataEntryDate
        {
            get
            {
                return this._DataEntryDate;
            }
            set
            {
                this.OnDataEntryDateChanging(value);
                this.ReportPropertyChanging("DataEntryDate");
                this._DataEntryDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DataEntryDate");
                this.OnDataEntryDateChanged();
            }
        }
        private global::System.DateTime _DataEntryDate;
        partial void OnDataEntryDateChanging(global::System.DateTime value);
        partial void OnDataEntryDateChanged();
        /// <summary>
        /// There are no comments for Property RecordDataType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordDataType
        {
            get
            {
                return this._RecordDataType;
            }
            set
            {
                this.OnRecordDataTypeChanging(value);
                this.ReportPropertyChanging("RecordDataType");
                this._RecordDataType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RecordDataType");
                this.OnRecordDataTypeChanged();
            }
        }
        private int _RecordDataType;
        partial void OnRecordDataTypeChanging(int value);
        partial void OnRecordDataTypeChanged();
        /// <summary>
        /// There are no comments for Property BelongToZone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool BelongToZone
        {
            get
            {
                return this._BelongToZone;
            }
            set
            {
                this.OnBelongToZoneChanging(value);
                this.ReportPropertyChanging("BelongToZone");
                this._BelongToZone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BelongToZone");
                this.OnBelongToZoneChanged();
            }
        }
        private bool _BelongToZone;
        partial void OnBelongToZoneChanging(bool value);
        partial void OnBelongToZoneChanged();
        /// <summary>
        /// There are no comments for Property ParentObjectID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> ParentObjectID
        {
            get
            {
                return this._ParentObjectID;
            }
            set
            {
                this.OnParentObjectIDChanging(value);
                this.ReportPropertyChanging("ParentObjectID");
                this._ParentObjectID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentObjectID");
                this.OnParentObjectIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _ParentObjectID;
        partial void OnParentObjectIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnParentObjectIDChanged();
    }
    /// <summary>
    /// There are no comments for JOMSQLDBModel.Region in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ZoneID
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="JOMSQLDBModel", Name="Region")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Region : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Region object.
        /// </summary>
        /// <param name="regionID">Initial value of RegionID.</param>
        /// <param name="polyData">Initial value of PolyData.</param>
        /// <param name="zoneID">Initial value of ZoneID.</param>
        /// <param name="id">Initial value of ID.</param>
        public static Region CreateRegion(string regionID, string polyData, global::System.Guid zoneID, global::System.Guid id)
        {
            Region region = new Region();
            region.RegionID = regionID;
            region.PolyData = polyData;
            region.ZoneID = zoneID;
            region.ID = id;
            return region;
        }
        /// <summary>
        /// There are no comments for Property RegionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionID
        {
            get
            {
                return this._RegionID;
            }
            set
            {
                this.OnRegionIDChanging(value);
                this.ReportPropertyChanging("RegionID");
                this._RegionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("RegionID");
                this.OnRegionIDChanged();
            }
        }
        private string _RegionID;
        partial void OnRegionIDChanging(string value);
        partial void OnRegionIDChanged();
        /// <summary>
        /// There are no comments for Property ArName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ArName
        {
            get
            {
                return this._ArName;
            }
            set
            {
                this.OnArNameChanging(value);
                this.ReportPropertyChanging("ArName");
                this._ArName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ArName");
                this.OnArNameChanged();
            }
        }
        private string _ArName;
        partial void OnArNameChanging(string value);
        partial void OnArNameChanged();
        /// <summary>
        /// There are no comments for Property EnName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this._EnName;
            }
            set
            {
                this.OnEnNameChanging(value);
                this.ReportPropertyChanging("EnName");
                this._EnName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EnName");
                this.OnEnNameChanged();
            }
        }
        private string _EnName;
        partial void OnEnNameChanging(string value);
        partial void OnEnNameChanged();
        /// <summary>
        /// There are no comments for Property PolyData in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PolyData
        {
            get
            {
                return this._PolyData;
            }
            set
            {
                this.OnPolyDataChanging(value);
                this.ReportPropertyChanging("PolyData");
                this._PolyData = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PolyData");
                this.OnPolyDataChanged();
            }
        }
        private string _PolyData;
        partial void OnPolyDataChanging(string value);
        partial void OnPolyDataChanged();
        /// <summary>
        /// There are no comments for Property ZoneID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ZoneID
        {
            get
            {
                return this._ZoneID;
            }
            set
            {
                this.OnZoneIDChanging(value);
                this.ReportPropertyChanging("ZoneID");
                this._ZoneID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ZoneID");
                this.OnZoneIDChanged();
            }
        }
        private global::System.Guid _ZoneID;
        partial void OnZoneIDChanging(global::System.Guid value);
        partial void OnZoneIDChanged();
        /// <summary>
        /// There are no comments for Property ZoomFactor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> ZoomFactor
        {
            get
            {
                return this._ZoomFactor;
            }
            set
            {
                this.OnZoomFactorChanging(value);
                this.ReportPropertyChanging("ZoomFactor");
                this._ZoomFactor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ZoomFactor");
                this.OnZoomFactorChanged();
            }
        }
        private global::System.Nullable<double> _ZoomFactor;
        partial void OnZoomFactorChanging(global::System.Nullable<double> value);
        partial void OnZoomFactorChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property FillColorR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FillColorR
        {
            get
            {
                return this._FillColorR;
            }
            set
            {
                this.OnFillColorRChanging(value);
                this.ReportPropertyChanging("FillColorR");
                this._FillColorR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FillColorR");
                this.OnFillColorRChanged();
            }
        }
        private global::System.Nullable<int> _FillColorR;
        partial void OnFillColorRChanging(global::System.Nullable<int> value);
        partial void OnFillColorRChanged();
        /// <summary>
        /// There are no comments for Property FillColorG in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FillColorG
        {
            get
            {
                return this._FillColorG;
            }
            set
            {
                this.OnFillColorGChanging(value);
                this.ReportPropertyChanging("FillColorG");
                this._FillColorG = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FillColorG");
                this.OnFillColorGChanged();
            }
        }
        private global::System.Nullable<int> _FillColorG;
        partial void OnFillColorGChanging(global::System.Nullable<int> value);
        partial void OnFillColorGChanged();
        /// <summary>
        /// There are no comments for Property FillColorB in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FillColorB
        {
            get
            {
                return this._FillColorB;
            }
            set
            {
                this.OnFillColorBChanging(value);
                this.ReportPropertyChanging("FillColorB");
                this._FillColorB = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FillColorB");
                this.OnFillColorBChanged();
            }
        }
        private global::System.Nullable<int> _FillColorB;
        partial void OnFillColorBChanging(global::System.Nullable<int> value);
        partial void OnFillColorBChanged();
        /// <summary>
        /// There are no comments for Property TranslateX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> TranslateX
        {
            get
            {
                return this._TranslateX;
            }
            set
            {
                this.OnTranslateXChanging(value);
                this.ReportPropertyChanging("TranslateX");
                this._TranslateX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TranslateX");
                this.OnTranslateXChanged();
            }
        }
        private global::System.Nullable<double> _TranslateX;
        partial void OnTranslateXChanging(global::System.Nullable<double> value);
        partial void OnTranslateXChanged();
        /// <summary>
        /// There are no comments for Property TranslateY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> TranslateY
        {
            get
            {
                return this._TranslateY;
            }
            set
            {
                this.OnTranslateYChanging(value);
                this.ReportPropertyChanging("TranslateY");
                this._TranslateY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TranslateY");
                this.OnTranslateYChanged();
            }
        }
        private global::System.Nullable<double> _TranslateY;
        partial void OnTranslateYChanging(global::System.Nullable<double> value);
        partial void OnTranslateYChanged();
        /// <summary>
        /// There are no comments for OwnerZone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("JOMSQLDBModel", "ZoneRegion", "Zone")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Zone OwnerZone
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Zone>("JOMSQLDBModel.ZoneRegion", "Zone").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Zone>("JOMSQLDBModel.ZoneRegion", "Zone").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OwnerZone in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Zone> OwnerZoneReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Zone>("JOMSQLDBModel.ZoneRegion", "Zone");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Zone>("JOMSQLDBModel.ZoneRegion", "Zone", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for JOMSQLDBModel.Sections in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SectionID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="JOMSQLDBModel", Name="Sections")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Sections : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Sections object.
        /// </summary>
        /// <param name="sectionID">Initial value of SectionID.</param>
        public static Sections CreateSections(global::System.Guid sectionID)
        {
            Sections sections = new Sections();
            sections.SectionID = sectionID;
            return sections;
        }
        /// <summary>
        /// There are no comments for Property SectionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid SectionID
        {
            get
            {
                return this._SectionID;
            }
            set
            {
                this.OnSectionIDChanging(value);
                this.ReportPropertyChanging("SectionID");
                this._SectionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SectionID");
                this.OnSectionIDChanged();
            }
        }
        private global::System.Guid _SectionID;
        partial void OnSectionIDChanging(global::System.Guid value);
        partial void OnSectionIDChanged();
        /// <summary>
        /// There are no comments for Property ArName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ArName
        {
            get
            {
                return this._ArName;
            }
            set
            {
                this.OnArNameChanging(value);
                this.ReportPropertyChanging("ArName");
                this._ArName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ArName");
                this.OnArNameChanged();
            }
        }
        private string _ArName;
        partial void OnArNameChanging(string value);
        partial void OnArNameChanged();
        /// <summary>
        /// There are no comments for Property EnName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this._EnName;
            }
            set
            {
                this.OnEnNameChanging(value);
                this.ReportPropertyChanging("EnName");
                this._EnName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EnName");
                this.OnEnNameChanged();
            }
        }
        private string _EnName;
        partial void OnEnNameChanging(string value);
        partial void OnEnNameChanged();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("JOMSQLDBModel", "CatSection", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Category> Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Category>("JOMSQLDBModel.CatSection", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Category>("JOMSQLDBModel.CatSection", "Category", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for JOMSQLDBModel.Zone in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="JOMSQLDBModel", Name="Zone")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Zone : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Zone object.
        /// </summary>
        /// <param name="zoneID">Initial value of ZoneID.</param>
        /// <param name="id">Initial value of ID.</param>
        public static Zone CreateZone(string zoneID, global::System.Guid id)
        {
            Zone zone = new Zone();
            zone.ZoneID = zoneID;
            zone.ID = id;
            return zone;
        }
        /// <summary>
        /// There are no comments for Property ZoneID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneID
        {
            get
            {
                return this._ZoneID;
            }
            set
            {
                this.OnZoneIDChanging(value);
                this.ReportPropertyChanging("ZoneID");
                this._ZoneID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ZoneID");
                this.OnZoneIDChanged();
            }
        }
        private string _ZoneID;
        partial void OnZoneIDChanging(string value);
        partial void OnZoneIDChanged();
        /// <summary>
        /// There are no comments for Property ArName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ArName
        {
            get
            {
                return this._ArName;
            }
            set
            {
                this.OnArNameChanging(value);
                this.ReportPropertyChanging("ArName");
                this._ArName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ArName");
                this.OnArNameChanged();
            }
        }
        private string _ArName;
        partial void OnArNameChanging(string value);
        partial void OnArNameChanged();
        /// <summary>
        /// There are no comments for Property EnName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this._EnName;
            }
            set
            {
                this.OnEnNameChanging(value);
                this.ReportPropertyChanging("EnName");
                this._EnName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EnName");
                this.OnEnNameChanged();
            }
        }
        private string _EnName;
        partial void OnEnNameChanging(string value);
        partial void OnEnNameChanged();
        /// <summary>
        /// There are no comments for Property PolyData in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PolyData
        {
            get
            {
                return this._PolyData;
            }
            set
            {
                this.OnPolyDataChanging(value);
                this.ReportPropertyChanging("PolyData");
                this._PolyData = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PolyData");
                this.OnPolyDataChanged();
            }
        }
        private string _PolyData;
        partial void OnPolyDataChanging(string value);
        partial void OnPolyDataChanged();
        /// <summary>
        /// There are no comments for Property ZoomFactor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> ZoomFactor
        {
            get
            {
                return this._ZoomFactor;
            }
            set
            {
                this.OnZoomFactorChanging(value);
                this.ReportPropertyChanging("ZoomFactor");
                this._ZoomFactor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ZoomFactor");
                this.OnZoomFactorChanged();
            }
        }
        private global::System.Nullable<double> _ZoomFactor;
        partial void OnZoomFactorChanging(global::System.Nullable<double> value);
        partial void OnZoomFactorChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property TranslateX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> TranslateX
        {
            get
            {
                return this._TranslateX;
            }
            set
            {
                this.OnTranslateXChanging(value);
                this.ReportPropertyChanging("TranslateX");
                this._TranslateX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TranslateX");
                this.OnTranslateXChanged();
            }
        }
        private global::System.Nullable<double> _TranslateX;
        partial void OnTranslateXChanging(global::System.Nullable<double> value);
        partial void OnTranslateXChanged();
        /// <summary>
        /// There are no comments for Property TranslateY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> TranslateY
        {
            get
            {
                return this._TranslateY;
            }
            set
            {
                this.OnTranslateYChanging(value);
                this.ReportPropertyChanging("TranslateY");
                this._TranslateY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TranslateY");
                this.OnTranslateYChanged();
            }
        }
        private global::System.Nullable<double> _TranslateY;
        partial void OnTranslateYChanging(global::System.Nullable<double> value);
        partial void OnTranslateYChanged();
        /// <summary>
        /// There are no comments for Property FillColorR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FillColorR
        {
            get
            {
                return this._FillColorR;
            }
            set
            {
                this.OnFillColorRChanging(value);
                this.ReportPropertyChanging("FillColorR");
                this._FillColorR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FillColorR");
                this.OnFillColorRChanged();
            }
        }
        private global::System.Nullable<int> _FillColorR;
        partial void OnFillColorRChanging(global::System.Nullable<int> value);
        partial void OnFillColorRChanged();
        /// <summary>
        /// There are no comments for Property FillColorG in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FillColorG
        {
            get
            {
                return this._FillColorG;
            }
            set
            {
                this.OnFillColorGChanging(value);
                this.ReportPropertyChanging("FillColorG");
                this._FillColorG = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FillColorG");
                this.OnFillColorGChanged();
            }
        }
        private global::System.Nullable<int> _FillColorG;
        partial void OnFillColorGChanging(global::System.Nullable<int> value);
        partial void OnFillColorGChanged();
        /// <summary>
        /// There are no comments for Property FillColorB in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FillColorB
        {
            get
            {
                return this._FillColorB;
            }
            set
            {
                this.OnFillColorBChanging(value);
                this.ReportPropertyChanging("FillColorB");
                this._FillColorB = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FillColorB");
                this.OnFillColorBChanged();
            }
        }
        private global::System.Nullable<int> _FillColorB;
        partial void OnFillColorBChanging(global::System.Nullable<int> value);
        partial void OnFillColorBChanged();
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("JOMSQLDBModel", "ZoneRegion", "Region")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Region> Regions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Region>("JOMSQLDBModel.ZoneRegion", "Region");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Region>("JOMSQLDBModel.ZoneRegion", "Region", value);
                }
            }
        }
    }
}
